// Generated by tools/generate_effects.py.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Transition;
using YMM4.ExtendedEffectsPack.Effects;

namespace YMM4.ExtendedEffectsPack.Transitions;

public sealed class MatrixRainTransitionPlugin : ITransitionPlugin
{
    public string Name => "EEP / マトリックス";
    public ITransitionParameter CreateTransitionParameter() => new MatrixRainTransitionParameter();
}

public sealed class MatrixRainTransitionParameter : PackTransitionParameter
{
    public override int EffectId => 8;
    private MatrixRainPreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public MatrixRainPreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private MatrixRainModeChoice mode = MatrixRainModeChoice.Option0;
    [Display(Name = "合成モード", Order = 1)]
    [EnumComboBox]
    public MatrixRainModeChoice Mode { get => mode; set => Set(ref mode, value); }

    private Animation speed = new Animation(2.5, 0.5, 10);
    [Display(Name = "落下速度", Order = 2)]
    [AnimationSlider("F2", "", 0.5, 10)]
    public Animation Speed { get => speed; set => Set(ref speed, value); }

    private Animation size = new Animation(18, 8, 48);
    [Display(Name = "文字サイズ", Order = 3)]
    [AnimationSlider("F2", "px", 8, 48)]
    public Animation Size { get => size; set => Set(ref size, value); }

    private MatrixRainCharsetChoice charset = MatrixRainCharsetChoice.Option0;
    [Display(Name = "文字種", Order = 4)]
    [EnumComboBox]
    public MatrixRainCharsetChoice Charset { get => charset; set => Set(ref charset, value); }

    private Animation tail = new Animation(14, 5, 30);
    [Display(Name = "残光の長さ", Order = 5)]
    [AnimationSlider("F2", "文字", 5, 30)]
    public Animation Tail { get => tail; set => Set(ref tail, value); }

    private Animation progress = new Animation(100, 0, 100);
    [System.ComponentModel.Browsable(false)]
    public Animation Progress { get => progress; set => Set(ref progress, value); }

    private Color tint = Color.FromRgb(0, 255, 65);
    [Display(Name = "文字カラー", Order = 7)]
    [ColorPicker]
    public Color Tint { get => tint; set => Set(ref tint, value); }

    private void ApplyPreset(MatrixRainPreset value)
    {
        switch (value)
        {
            case MatrixRainPreset.Option0:
                Mode = MatrixRainModeChoice.Option0;
                Speed = new Animation(2.5, 0.5, 10);
                Size = new Animation(18, 8, 48);
                Charset = MatrixRainCharsetChoice.Option0;
                Tail = new Animation(14, 5, 30);
                Progress = new Animation(100, 0, 100);
                Tint = Color.FromRgb(0, 255, 65);
                break;
            case MatrixRainPreset.Option1:
                Mode = MatrixRainModeChoice.Option1;
                Speed = new Animation(2.5, 0.5, 10);
                Size = new Animation(18, 8, 48);
                Charset = MatrixRainCharsetChoice.Option0;
                Tail = new Animation(14, 5, 30);
                Progress = new Animation(100, 0, 100);
                Tint = Color.FromRgb(0, 255, 65);
                break;
            case MatrixRainPreset.Option2:
                Mode = MatrixRainModeChoice.Option0;
                Speed = new Animation(2.5, 0.5, 10);
                Size = new Animation(14, 8, 48);
                Charset = MatrixRainCharsetChoice.Option2;
                Tail = new Animation(14, 5, 30);
                Progress = new Animation(100, 0, 100);
                Tint = Color.FromRgb(0, 255, 65);
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [(float)Mode, Value(Speed, frame, length, fps), Value(Size, frame, length, fps), (float)Charset, Value(Tail, frame, length, fps), Value(Progress, frame, length, fps)];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [Speed, Size, Tail, Progress];
    internal override Vector4 ReadTint() => new(Tint.R / 255f, Tint.G / 255f, Tint.B / 255f, Tint.A / 255f);
}
