// Generated by tools/generate_effects.py.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Transition;
using YMM4.ExtendedEffectsPack.Effects;

namespace YMM4.ExtendedEffectsPack.Transitions;

public sealed class PrismWhipTransitionPlugin : ITransitionPlugin
{
    public string Name => "EEP / プリズム・ウィップ";
    public ITransitionParameter CreateTransitionParameter() => new PrismWhipTransitionParameter();
}

public sealed class PrismWhipTransitionParameter : PackTransitionParameter
{
    public override int EffectId => 16;
    private PrismWhipPreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public PrismWhipPreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private Animation progress = new Animation(0, 0, 100);
    [System.ComponentModel.Browsable(false)]
    public Animation Progress { get => progress; set => Set(ref progress, value); }

    private Animation angle = new Animation(0, 0, 360);
    [Display(Name = "パン角度", Order = 2)]
    [AnimationSlider("F2", "°", 0, 360)]
    public Animation Angle { get => angle; set => Set(ref angle, value); }

    private Animation blur = new Animation(0.5, 0, 1);
    [Display(Name = "方向ブラー", Order = 3)]
    [AnimationSlider("F2", "", 0, 1)]
    public Animation Blur { get => blur; set => Set(ref blur, value); }

    private Animation chromatic = new Animation(12, 0, 40);
    [Display(Name = "色収差", Order = 4)]
    [AnimationSlider("F2", "px", 0, 40)]
    public Animation Chromatic { get => chromatic; set => Set(ref chromatic, value); }

    private Animation zoom = new Animation(15, 0, 50);
    [Display(Name = "ズーム", Order = 5)]
    [AnimationSlider("F2", "%", 0, 50)]
    public Animation Zoom { get => zoom; set => Set(ref zoom, value); }

    private void ApplyPreset(PrismWhipPreset value)
    {
        switch (value)
        {
            case PrismWhipPreset.Option0:
                Progress = new Animation(0, 0, 100);
                Angle = new Animation(0, 0, 360);
                Blur = new Animation(0.5, 0, 1);
                Chromatic = new Animation(12, 0, 40);
                Zoom = new Animation(15, 0, 50);
                break;
            case PrismWhipPreset.Option1:
                Progress = new Animation(0, 0, 100);
                Angle = new Animation(90, 0, 360);
                Blur = new Animation(0.5, 0, 1);
                Chromatic = new Animation(12, 0, 40);
                Zoom = new Animation(15, 0, 50);
                break;
            case PrismWhipPreset.Option2:
                Progress = new Animation(0, 0, 100);
                Angle = new Animation(35, 0, 360);
                Blur = new Animation(0.8, 0, 1);
                Chromatic = new Animation(30, 0, 40);
                Zoom = new Animation(15, 0, 50);
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [Value(Progress, frame, length, fps), Value(Angle, frame, length, fps), Value(Blur, frame, length, fps), Value(Chromatic, frame, length, fps), Value(Zoom, frame, length, fps)];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [Progress, Angle, Blur, Chromatic, Zoom];
}
