// Generated by tools/generate_effects.py. Edit the catalog, then regenerate.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Effects;
using YMM4.ExtendedEffectsPack.Common;

namespace YMM4.ExtendedEffectsPack.Effects;

public enum BlinkPreset
{
    [Display(Name = "目覚め")] Option0,
    [Display(Name = "通常まばたき")] Option1,
    [Display(Name = "気絶・意識消失")] Option2,
    [Display(Name = "自動パチパチ")] Option3,
}

[VideoEffect("EEP / まばたき", ["Extended Effects Pack"], ["EEP"], IsAviUtlSupported = false)]
public sealed class BlinkEffect : PackEffect
{
    public override string Label => "まばたき";
    public override int EffectId => 1;
    private BlinkPreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public BlinkPreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private Animation progress = new Animation(0, 0, 100);
    [Display(Name = "開き具合", Order = 1)]
    [AnimationSlider("F2", "%", 0, 100)]
    public Animation Progress { get => progress; set => Set(ref progress, value); }

    private bool autoLoop = false;
    [Display(Name = "自動ループ", Order = 2)]
    [ToggleSlider]
    public bool AutoLoop { get => autoLoop; set => Set(ref autoLoop, value); }

    private Animation frequency = new Animation(18, 5, 60);
    [Display(Name = "まばたき頻度", Order = 3)]
    [AnimationSlider("F2", "回/分", 5, 60)]
    public Animation Frequency { get => frequency; set => Set(ref frequency, value); }

    private Animation blur = new Animation(18, 0, 20);
    [Display(Name = "ピンボケ強度", Order = 4)]
    [AnimationSlider("F2", "px", 0, 20)]
    public Animation Blur { get => blur; set => Set(ref blur, value); }

    private Color tint = Color.FromRgb(0, 0, 0);
    [Display(Name = "まぶたの色", Order = 5)]
    [ColorPicker]
    public Color Tint { get => tint; set => Set(ref tint, value); }

    private void ApplyPreset(BlinkPreset value)
    {
        switch (value)
        {
            case BlinkPreset.Option0:
                Progress = new Animation(0, 0, 100);
                AutoLoop = false;
                Frequency = new Animation(18, 5, 60);
                Blur = new Animation(18, 0, 20);
                Tint = Color.FromRgb(0, 0, 0);
                break;
            case BlinkPreset.Option1:
                Progress = new Animation(100, 0, 100);
                AutoLoop = false;
                Frequency = new Animation(18, 5, 60);
                Blur = new Animation(4, 0, 20);
                Tint = Color.FromRgb(0, 0, 0);
                break;
            case BlinkPreset.Option2:
                Progress = new Animation(10, 0, 100);
                AutoLoop = false;
                Frequency = new Animation(18, 5, 60);
                Blur = new Animation(20, 0, 20);
                Tint = Color.FromRgb(0, 0, 0);
                break;
            case BlinkPreset.Option3:
                Progress = new Animation(100, 0, 100);
                AutoLoop = true;
                Frequency = new Animation(18, 5, 60);
                Blur = new Animation(2, 0, 20);
                Tint = Color.FromRgb(0, 0, 0);
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [Value(Progress, frame, length, fps), AutoLoop ? 1 : 0, Value(Frequency, frame, length, fps), Value(Blur, frame, length, fps)];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [Progress, Frequency, Blur];
    internal override Vector4 ReadTint() => new(Tint.R / 255f, Tint.G / 255f, Tint.B / 255f, Tint.A / 255f);
}
