// Generated by tools/generate_effects.py. Edit the catalog, then regenerate.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Effects;
using YMM4.ExtendedEffectsPack.Common;

namespace YMM4.ExtendedEffectsPack.Effects;

public enum BlockWavePreset
{
    [Display(Name = "デジタル水平波")] Option0,
    [Display(Name = "中央リップル")] Option1,
    [Display(Name = "立体ブロック")] Option2,
}

public enum BlockWaveDirectionChoice
{
    [Display(Name = "水平")] Option0,
    [Display(Name = "垂直")] Option1,
    [Display(Name = "中央放射")] Option2,
}

public enum BlockWaveWaveformChoice
{
    [Display(Name = "正弦波")] Option0,
    [Display(Name = "デジタルステップ")] Option1,
}

[VideoEffect("EEP / ブロックウェーブ", ["Extended Effects Pack"], ["EEP"], IsAviUtlSupported = false)]
public sealed class BlockWaveEffect : PackEffect
{
    public override string Label => "ブロックウェーブ";
    public override int EffectId => 5;
    private BlockWavePreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public BlockWavePreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private Animation count = new Animation(20, 5, 100);
    [Display(Name = "分割数", Order = 1)]
    [AnimationSlider("F2", "", 5, 100)]
    public Animation Count { get => count; set => Set(ref count, value); }

    private BlockWaveDirectionChoice direction = BlockWaveDirectionChoice.Option0;
    [Display(Name = "波の進行方向", Order = 2)]
    [EnumComboBox]
    public BlockWaveDirectionChoice Direction { get => direction; set => Set(ref direction, value); }

    private BlockWaveWaveformChoice waveform = BlockWaveWaveformChoice.Option1;
    [Display(Name = "波の形状", Order = 3)]
    [EnumComboBox]
    public BlockWaveWaveformChoice Waveform { get => waveform; set => Set(ref waveform, value); }

    private Animation amplitude = new Animation(30, 0, 150);
    [Display(Name = "ズレ強度", Order = 4)]
    [AnimationSlider("F2", "px", 0, 150)]
    public Animation Amplitude { get => amplitude; set => Set(ref amplitude, value); }

    private Animation speed = new Animation(2, 0.1, 10);
    [Display(Name = "波の速度", Order = 5)]
    [AnimationSlider("F2", "", 0.1, 10)]
    public Animation Speed { get => speed; set => Set(ref speed, value); }

    private bool border = true;
    [Display(Name = "ブロック境界線", Order = 6)]
    [ToggleSlider]
    public bool Border { get => border; set => Set(ref border, value); }

    private Animation progress = new Animation(100, 0, 100);
    [Display(Name = "進行度（切替用）", Order = 7)]
    [AnimationSlider("F2", "%", 0, 100)]
    public Animation Progress { get => progress; set => Set(ref progress, value); }

    private void ApplyPreset(BlockWavePreset value)
    {
        switch (value)
        {
            case BlockWavePreset.Option0:
                Count = new Animation(20, 5, 100);
                Direction = BlockWaveDirectionChoice.Option0;
                Waveform = BlockWaveWaveformChoice.Option1;
                Amplitude = new Animation(30, 0, 150);
                Speed = new Animation(2, 0.1, 10);
                Border = true;
                Progress = new Animation(100, 0, 100);
                break;
            case BlockWavePreset.Option1:
                Count = new Animation(35, 5, 100);
                Direction = BlockWaveDirectionChoice.Option2;
                Waveform = BlockWaveWaveformChoice.Option0;
                Amplitude = new Animation(30, 0, 150);
                Speed = new Animation(2, 0.1, 10);
                Border = true;
                Progress = new Animation(100, 0, 100);
                break;
            case BlockWavePreset.Option2:
                Count = new Animation(10, 5, 100);
                Direction = BlockWaveDirectionChoice.Option0;
                Waveform = BlockWaveWaveformChoice.Option0;
                Amplitude = new Animation(60, 0, 150);
                Speed = new Animation(2, 0.1, 10);
                Border = true;
                Progress = new Animation(100, 0, 100);
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [Value(Count, frame, length, fps), (float)Direction, (float)Waveform, Value(Amplitude, frame, length, fps), Value(Speed, frame, length, fps), Border ? 1 : 0, Value(Progress, frame, length, fps)];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [Count, Amplitude, Speed, Progress];
}
