// Generated by tools/generate_effects.py. Edit the catalog, then regenerate.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Effects;
using YMM4.ExtendedEffectsPack.Common;

namespace YMM4.ExtendedEffectsPack.Effects;

public enum CameraShakeZoomPreset
{
    [Display(Name = "ビートドロップ")] Option0,
    [Display(Name = "激震ツッコミ")] Option1,
    [Display(Name = "映画的スロー")] Option2,
}

[VideoEffect("EEP / スマートズームブラー＆シェイク", ["Extended Effects Pack"], ["EEP"], IsAviUtlSupported = false)]
public sealed class CameraShakeZoomEffect : PackEffect
{
    public override string Label => "スマートズームブラー＆シェイク";
    public override int EffectId => 10;
    private CameraShakeZoomPreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public CameraShakeZoomPreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private Animation shake = new Animation(25, 0, 100);
    [Display(Name = "揺れ強度", Order = 1)]
    [AnimationSlider("F2", "px", 0, 100)]
    public Animation Shake { get => shake; set => Set(ref shake, value); }

    private Animation blur = new Animation(0.4, 0, 1);
    [Display(Name = "放射ブラー強度", Order = 2)]
    [AnimationSlider("F2", "", 0, 1)]
    public Animation Blur { get => blur; set => Set(ref blur, value); }

    private Animation frequency = new Animation(24, 1, 60);
    [Display(Name = "振動速度", Order = 3)]
    [AnimationSlider("F2", "Hz", 1, 60)]
    public Animation Frequency { get => frequency; set => Set(ref frequency, value); }

    private Animation zoom = new Animation(12, 0, 50);
    [Display(Name = "中心ズーム率", Order = 4)]
    [AnimationSlider("F2", "%", 0, 50)]
    public Animation Zoom { get => zoom; set => Set(ref zoom, value); }

    private Animation decay = new Animation(0.5, 0.1, 2);
    [Display(Name = "減衰時間", Order = 5)]
    [AnimationSlider("F2", "秒", 0.1, 2)]
    public Animation Decay { get => decay; set => Set(ref decay, value); }

    private void ApplyPreset(CameraShakeZoomPreset value)
    {
        switch (value)
        {
            case CameraShakeZoomPreset.Option0:
                Shake = new Animation(25, 0, 100);
                Blur = new Animation(0.4, 0, 1);
                Frequency = new Animation(24, 1, 60);
                Zoom = new Animation(12, 0, 50);
                Decay = new Animation(0.5, 0.1, 2);
                break;
            case CameraShakeZoomPreset.Option1:
                Shake = new Animation(70, 0, 100);
                Blur = new Animation(0.65, 0, 1);
                Frequency = new Animation(24, 1, 60);
                Zoom = new Animation(12, 0, 50);
                Decay = new Animation(0.3, 0.1, 2);
                break;
            case CameraShakeZoomPreset.Option2:
                Shake = new Animation(8, 0, 100);
                Blur = new Animation(0.4, 0, 1);
                Frequency = new Animation(5, 1, 60);
                Zoom = new Animation(12, 0, 50);
                Decay = new Animation(1.5, 0.1, 2);
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [Value(Shake, frame, length, fps), Value(Blur, frame, length, fps), Value(Frequency, frame, length, fps), Value(Zoom, frame, length, fps), Value(Decay, frame, length, fps)];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [Shake, Blur, Frequency, Zoom, Decay];
}
