// Generated by tools/generate_effects.py. Edit the catalog, then regenerate.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Effects;
using YMM4.ExtendedEffectsPack.Common;

namespace YMM4.ExtendedEffectsPack.Effects;

public enum FilmBurnPreset
{
    [Display(Name = "ヴィンテージオレンジ")] Option0,
    [Display(Name = "シネマティックプリズム")] Option1,
    [Display(Name = "フラッシュ切替")] Option2,
}

public enum FilmBurnPaletteChoice
{
    [Display(Name = "ウォームオレンジ")] Option0,
    [Display(Name = "パステルプリズム")] Option1,
    [Display(Name = "クールシアン")] Option2,
}

[VideoEffect("EEP / フィルムバーン＆ライトリーク", ["Extended Effects Pack"], ["EEP"], IsAviUtlSupported = false)]
public sealed class FilmBurnEffect : PackEffect
{
    public override string Label => "フィルムバーン＆ライトリーク";
    public override int EffectId => 11;
    private FilmBurnPreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public FilmBurnPreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private Animation progress = new Animation(0, 0, 100);
    [Display(Name = "進行度", Order = 1)]
    [AnimationSlider("F2", "%", 0, 100)]
    public Animation Progress { get => progress; set => Set(ref progress, value); }

    private FilmBurnPaletteChoice palette = FilmBurnPaletteChoice.Option0;
    [Display(Name = "光の色調", Order = 2)]
    [EnumComboBox]
    public FilmBurnPaletteChoice Palette { get => palette; set => Set(ref palette, value); }

    private Animation width = new Animation(0.8, 0.1, 2);
    [Display(Name = "感光の広がり幅", Order = 3)]
    [AnimationSlider("F2", "", 0.1, 2)]
    public Animation Width { get => width; set => Set(ref width, value); }

    private bool grain = true;
    [Display(Name = "フィルム粒子", Order = 4)]
    [ToggleSlider]
    public bool Grain { get => grain; set => Set(ref grain, value); }

    private bool darken = false;
    [Display(Name = "焼きつき暗転", Order = 5)]
    [ToggleSlider]
    public bool Darken { get => darken; set => Set(ref darken, value); }

    private void ApplyPreset(FilmBurnPreset value)
    {
        switch (value)
        {
            case FilmBurnPreset.Option0:
                Progress = new Animation(0, 0, 100);
                Palette = FilmBurnPaletteChoice.Option0;
                Width = new Animation(0.8, 0.1, 2);
                Grain = true;
                Darken = false;
                break;
            case FilmBurnPreset.Option1:
                Progress = new Animation(0, 0, 100);
                Palette = FilmBurnPaletteChoice.Option1;
                Width = new Animation(1.2, 0.1, 2);
                Grain = true;
                Darken = false;
                break;
            case FilmBurnPreset.Option2:
                Progress = new Animation(0, 0, 100);
                Palette = FilmBurnPaletteChoice.Option0;
                Width = new Animation(1.8, 0.1, 2);
                Grain = false;
                Darken = false;
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [Value(Progress, frame, length, fps), (float)Palette, Value(Width, frame, length, fps), Grain ? 1 : 0, Darken ? 1 : 0];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [Progress, Width];
}
