// Generated by tools/generate_effects.py. Edit the catalog, then regenerate.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Effects;
using YMM4.ExtendedEffectsPack.Common;

namespace YMM4.ExtendedEffectsPack.Effects;

public enum GodRaysPreset
{
    [Display(Name = "降り注ぐ木漏れ日")] Option0,
    [Display(Name = "神の降臨")] Option1,
    [Display(Name = "夕日サンセット")] Option2,
}

[VideoEffect("EEP / ゴッドレイ・多条光線", ["Extended Effects Pack"], ["EEP"], IsAviUtlSupported = false)]
public sealed class GodRaysEffect : PackEffect
{
    public override string Label => "ゴッドレイ・多条光線";
    public override int EffectId => 7;
    private GodRaysPreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public GodRaysPreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private Animation lightX = new Animation(0.5, -1, 2);
    [Display(Name = "光源X", Order = 1)]
    [AnimationSlider("F2", "", -1, 2)]
    public Animation LightX { get => lightX; set => Set(ref lightX, value); }

    private Animation lightY = new Animation(-0.2, -1, 2);
    [Display(Name = "光源Y", Order = 2)]
    [AnimationSlider("F2", "", -1, 2)]
    public Animation LightY { get => lightY; set => Set(ref lightY, value); }

    private Animation density = new Animation(24, 5, 50);
    [Display(Name = "光筋の密度", Order = 3)]
    [AnimationSlider("F2", "", 5, 50)]
    public Animation Density { get => density; set => Set(ref density, value); }

    private Animation length = new Animation(0.85, 0.1, 1);
    [Display(Name = "光条の長さ", Order = 4)]
    [AnimationSlider("F2", "", 0.1, 1)]
    public Animation Length { get => length; set => Set(ref length, value); }

    private Animation noise = new Animation(0.6, 0, 1);
    [Display(Name = "雲間ノイズ", Order = 5)]
    [AnimationSlider("F2", "", 0, 1)]
    public Animation Noise { get => noise; set => Set(ref noise, value); }

    private Animation width = new Animation(0.4, 0.05, 1);
    [Display(Name = "光筋の太さ", Order = 6)]
    [AnimationSlider("F2", "", 0.05, 1)]
    public Animation Width { get => width; set => Set(ref width, value); }

    private Color tint = Color.FromRgb(255, 243, 208);
    [Display(Name = "光の色", Order = 7)]
    [ColorPicker]
    public Color Tint { get => tint; set => Set(ref tint, value); }

    private void ApplyPreset(GodRaysPreset value)
    {
        switch (value)
        {
            case GodRaysPreset.Option0:
                LightX = new Animation(0.5, -1, 2);
                LightY = new Animation(-0.2, -1, 2);
                Density = new Animation(24, 5, 50);
                Length = new Animation(0.85, 0.1, 1);
                Noise = new Animation(0.6, 0, 1);
                Width = new Animation(0.4, 0.05, 1);
                Tint = Color.FromRgb(255, 243, 208);
                break;
            case GodRaysPreset.Option1:
                LightX = new Animation(0.5, -1, 2);
                LightY = new Animation(0.5, -1, 2);
                Density = new Animation(40, 5, 50);
                Length = new Animation(0.85, 0.1, 1);
                Noise = new Animation(0.25, 0, 1);
                Width = new Animation(0.4, 0.05, 1);
                Tint = Color.FromRgb(255, 243, 208);
                break;
            case GodRaysPreset.Option2:
                LightX = new Animation(1.1, -1, 2);
                LightY = new Animation(0.15, -1, 2);
                Density = new Animation(24, 5, 50);
                Length = new Animation(0.85, 0.1, 1);
                Noise = new Animation(0.6, 0, 1);
                Width = new Animation(0.4, 0.05, 1);
                Tint = Color.FromRgb(255, 134, 48);
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [Value(LightX, frame, length, fps), Value(LightY, frame, length, fps), Value(Density, frame, length, fps), Value(Length, frame, length, fps), Value(Noise, frame, length, fps), Value(Width, frame, length, fps)];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [LightX, LightY, Density, Length, Noise, Width];
    internal override Vector4 ReadTint() => new(Tint.R / 255f, Tint.G / 255f, Tint.B / 255f, Tint.A / 255f);
}
