// Generated by tools/generate_effects.py. Edit the catalog, then regenerate.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Effects;
using YMM4.ExtendedEffectsPack.Common;

namespace YMM4.ExtendedEffectsPack.Effects;

public enum HeartbeatPreset
{
    [Display(Name = "緊迫の心拍")] Option0,
    [Display(Name = "恐怖・瀕死")] Option1,
    [Display(Name = "ポップ弾み")] Option2,
}

public enum HeartbeatModeChoice
{
    [Display(Name = "ドッ・クン二連撃")] Option0,
    [Display(Name = "サイン波")] Option1,
}

[VideoEffect("EEP / 鼓動", ["Extended Effects Pack"], ["EEP"], IsAviUtlSupported = false)]
public sealed class HeartbeatEffect : PackEffect
{
    public override string Label => "鼓動";
    public override int EffectId => 3;
    private HeartbeatPreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public HeartbeatPreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private HeartbeatModeChoice mode = HeartbeatModeChoice.Option0;
    [Display(Name = "鼓動モード", Order = 1)]
    [EnumComboBox]
    public HeartbeatModeChoice Mode { get => mode; set => Set(ref mode, value); }

    private Animation bpm = new Animation(120, 30, 240);
    [Display(Name = "BPM", Order = 2)]
    [AnimationSlider("F2", "", 30, 240)]
    public Animation Bpm { get => bpm; set => Set(ref bpm, value); }

    private Animation scale = new Animation(8, 0, 30);
    [Display(Name = "拡縮強度", Order = 3)]
    [AnimationSlider("F2", "%", 0, 30)]
    public Animation Scale { get => scale; set => Set(ref scale, value); }

    private Animation flash = new Animation(0.5, 0, 1);
    [Display(Name = "周辺フラッシュ", Order = 4)]
    [AnimationSlider("F2", "", 0, 1)]
    public Animation Flash { get => flash; set => Set(ref flash, value); }

    private Animation chromatic = new Animation(5, 0, 15);
    [Display(Name = "色収差ブレ", Order = 5)]
    [AnimationSlider("F2", "px", 0, 15)]
    public Animation Chromatic { get => chromatic; set => Set(ref chromatic, value); }

    private Color tint = Color.FromRgb(128, 0, 0);
    [Display(Name = "フラッシュ色", Order = 6)]
    [ColorPicker]
    public Color Tint { get => tint; set => Set(ref tint, value); }

    private void ApplyPreset(HeartbeatPreset value)
    {
        switch (value)
        {
            case HeartbeatPreset.Option0:
                Mode = HeartbeatModeChoice.Option0;
                Bpm = new Animation(120, 30, 240);
                Scale = new Animation(8, 0, 30);
                Flash = new Animation(0.5, 0, 1);
                Chromatic = new Animation(5, 0, 15);
                Tint = Color.FromRgb(128, 0, 0);
                break;
            case HeartbeatPreset.Option1:
                Mode = HeartbeatModeChoice.Option0;
                Bpm = new Animation(40, 30, 240);
                Scale = new Animation(4, 0, 30);
                Flash = new Animation(0.7, 0, 1);
                Chromatic = new Animation(5, 0, 15);
                Tint = Color.FromRgb(128, 0, 0);
                break;
            case HeartbeatPreset.Option2:
                Mode = HeartbeatModeChoice.Option1;
                Bpm = new Animation(100, 30, 240);
                Scale = new Animation(12, 0, 30);
                Flash = new Animation(0, 0, 1);
                Chromatic = new Animation(0, 0, 15);
                Tint = Color.FromRgb(128, 0, 0);
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [(float)Mode, Value(Bpm, frame, length, fps), Value(Scale, frame, length, fps), Value(Flash, frame, length, fps), Value(Chromatic, frame, length, fps)];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [Bpm, Scale, Flash, Chromatic];
    internal override Vector4 ReadTint() => new(Tint.R / 255f, Tint.G / 255f, Tint.B / 255f, Tint.A / 255f);
    internal override double ReadClock(double frame, double length, int fps) => IntegratedBeats(Bpm, frame, length, fps);
}
