// Generated by tools/generate_effects.py. Edit the catalog, then regenerate.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Effects;
using YMM4.ExtendedEffectsPack.Common;

namespace YMM4.ExtendedEffectsPack.Effects;

public enum InkBleedPreset
{
    [Display(Name = "水彩にじみ")] Option0,
    [Display(Name = "墨の飛沫")] Option1,
    [Display(Name = "パステルインク")] Option2,
}

[VideoEffect("EEP / インクにじみ", ["Extended Effects Pack"], ["EEP"], IsAviUtlSupported = false)]
public sealed class InkBleedEffect : PackEffect
{
    public override string Label => "インクにじみ";
    public override int EffectId => 14;
    private InkBleedPreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public InkBleedPreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private Animation progress = new Animation(0, 0, 100);
    [Display(Name = "進行度", Order = 1)]
    [AnimationSlider("F2", "%", 0, 100)]
    public Animation Progress { get => progress; set => Set(ref progress, value); }

    private Animation scale = new Animation(6, 1, 20);
    [Display(Name = "にじみ粒度", Order = 2)]
    [AnimationSlider("F2", "", 1, 20)]
    public Animation Scale { get => scale; set => Set(ref scale, value); }

    private Animation softness = new Animation(0.12, 0.01, 0.5);
    [Display(Name = "にじみ幅", Order = 3)]
    [AnimationSlider("F2", "", 0.01, 0.5)]
    public Animation Softness { get => softness; set => Set(ref softness, value); }

    private Animation seed = new Animation(7, 0, 1000);
    [Display(Name = "シード", Order = 4)]
    [AnimationSlider("F2", "", 0, 1000)]
    public Animation Seed { get => seed; set => Set(ref seed, value); }

    private Animation centerX = new Animation(0.5, 0, 1);
    [Display(Name = "中心X", Order = 5)]
    [AnimationSlider("F2", "", 0, 1)]
    public Animation CenterX { get => centerX; set => Set(ref centerX, value); }

    private Animation centerY = new Animation(0.5, 0, 1);
    [Display(Name = "中心Y", Order = 6)]
    [AnimationSlider("F2", "", 0, 1)]
    public Animation CenterY { get => centerY; set => Set(ref centerY, value); }

    private Color tint = Color.FromRgb(25, 18, 38);
    [Display(Name = "インク縁色", Order = 7)]
    [ColorPicker]
    public Color Tint { get => tint; set => Set(ref tint, value); }

    private void ApplyPreset(InkBleedPreset value)
    {
        switch (value)
        {
            case InkBleedPreset.Option0:
                Progress = new Animation(0, 0, 100);
                Scale = new Animation(6, 1, 20);
                Softness = new Animation(0.12, 0.01, 0.5);
                Seed = new Animation(7, 0, 1000);
                CenterX = new Animation(0.5, 0, 1);
                CenterY = new Animation(0.5, 0, 1);
                Tint = Color.FromRgb(25, 18, 38);
                break;
            case InkBleedPreset.Option1:
                Progress = new Animation(0, 0, 100);
                Scale = new Animation(12, 1, 20);
                Softness = new Animation(0.04, 0.01, 0.5);
                Seed = new Animation(7, 0, 1000);
                CenterX = new Animation(0.5, 0, 1);
                CenterY = new Animation(0.5, 0, 1);
                Tint = Color.FromRgb(3, 3, 3);
                break;
            case InkBleedPreset.Option2:
                Progress = new Animation(0, 0, 100);
                Scale = new Animation(3, 1, 20);
                Softness = new Animation(0.3, 0.01, 0.5);
                Seed = new Animation(7, 0, 1000);
                CenterX = new Animation(0.5, 0, 1);
                CenterY = new Animation(0.5, 0, 1);
                Tint = Color.FromRgb(194, 104, 171);
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [Value(Progress, frame, length, fps), Value(Scale, frame, length, fps), Value(Softness, frame, length, fps), Value(Seed, frame, length, fps), Value(CenterX, frame, length, fps), Value(CenterY, frame, length, fps)];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [Progress, Scale, Softness, Seed, CenterX, CenterY];
    internal override Vector4 ReadTint() => new(Tint.R / 255f, Tint.G / 255f, Tint.B / 255f, Tint.A / 255f);
}
