// Generated by tools/generate_effects.py. Edit the catalog, then regenerate.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Effects;
using YMM4.ExtendedEffectsPack.Common;

namespace YMM4.ExtendedEffectsPack.Effects;

public enum LivingFlamePreset
{
    [Display(Name = "紅蓮の業火")] Option0,
    [Display(Name = "陽炎・元色保持")] Option1,
    [Display(Name = "青い鬼火")] Option2,
    [Display(Name = "紫の魔炎")] Option3,
}

public enum LivingFlamePaletteChoice
{
    [Display(Name = "赤黄オレンジ")] Option0,
    [Display(Name = "青白い炎")] Option1,
    [Display(Name = "紫炎")] Option2,
}

[VideoEffect("EEP / 炎・画像炎化", ["Extended Effects Pack"], ["EEP"], IsAviUtlSupported = false)]
public sealed class LivingFlameEffect : PackEffect
{
    public override string Label => "炎・画像炎化";
    public override int EffectId => 6;
    private LivingFlamePreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public LivingFlamePreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private Animation distortion = new Animation(30, 0, 100);
    [Display(Name = "うねり変形度", Order = 1)]
    [AnimationSlider("F2", "", 0, 100)]
    public Animation Distortion { get => distortion; set => Set(ref distortion, value); }

    private Animation speed = new Animation(3, 0.1, 10);
    [Display(Name = "揺らぎ速度", Order = 2)]
    [AnimationSlider("F2", "", 0.1, 10)]
    public Animation Speed { get => speed; set => Set(ref speed, value); }

    private bool colorize = true;
    [Display(Name = "炎着色", Order = 3)]
    [ToggleSlider]
    public bool Colorize { get => colorize; set => Set(ref colorize, value); }

    private LivingFlamePaletteChoice palette = LivingFlamePaletteChoice.Option0;
    [Display(Name = "炎パレット", Order = 4)]
    [EnumComboBox]
    public LivingFlamePaletteChoice Palette { get => palette; set => Set(ref palette, value); }

    private bool sparks = true;
    [Display(Name = "火の粉", Order = 5)]
    [ToggleSlider]
    public bool Sparks { get => sparks; set => Set(ref sparks, value); }

    private Animation dissolve = new Animation(0, 0, 100);
    [Display(Name = "燃焼ディゾルブ", Order = 6)]
    [AnimationSlider("F2", "%", 0, 100)]
    public Animation Dissolve { get => dissolve; set => Set(ref dissolve, value); }

    private Animation colorMix = new Animation(0.85, 0, 1);
    [Display(Name = "着色ブレンド", Order = 7)]
    [AnimationSlider("F2", "", 0, 1)]
    public Animation ColorMix { get => colorMix; set => Set(ref colorMix, value); }

    private void ApplyPreset(LivingFlamePreset value)
    {
        switch (value)
        {
            case LivingFlamePreset.Option0:
                Distortion = new Animation(30, 0, 100);
                Speed = new Animation(3, 0.1, 10);
                Colorize = true;
                Palette = LivingFlamePaletteChoice.Option0;
                Sparks = true;
                Dissolve = new Animation(0, 0, 100);
                ColorMix = new Animation(0.85, 0, 1);
                break;
            case LivingFlamePreset.Option1:
                Distortion = new Animation(12, 0, 100);
                Speed = new Animation(3, 0.1, 10);
                Colorize = false;
                Palette = LivingFlamePaletteChoice.Option0;
                Sparks = false;
                Dissolve = new Animation(0, 0, 100);
                ColorMix = new Animation(0.85, 0, 1);
                break;
            case LivingFlamePreset.Option2:
                Distortion = new Animation(30, 0, 100);
                Speed = new Animation(3, 0.1, 10);
                Colorize = true;
                Palette = LivingFlamePaletteChoice.Option1;
                Sparks = true;
                Dissolve = new Animation(0, 0, 100);
                ColorMix = new Animation(0.85, 0, 1);
                break;
            case LivingFlamePreset.Option3:
                Distortion = new Animation(30, 0, 100);
                Speed = new Animation(3, 0.1, 10);
                Colorize = true;
                Palette = LivingFlamePaletteChoice.Option2;
                Sparks = true;
                Dissolve = new Animation(0, 0, 100);
                ColorMix = new Animation(0.85, 0, 1);
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [Value(Distortion, frame, length, fps), Value(Speed, frame, length, fps), Colorize ? 1 : 0, (float)Palette, Sparks ? 1 : 0, Value(Dissolve, frame, length, fps), Value(ColorMix, frame, length, fps)];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [Distortion, Speed, Dissolve, ColorMix];
}
