// Generated by tools/generate_effects.py. Edit the catalog, then regenerate.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Effects;
using YMM4.ExtendedEffectsPack.Common;

namespace YMM4.ExtendedEffectsPack.Effects;

public enum LumaMeltPreset
{
    [Display(Name = "ハイライト溶解")] Option0,
    [Display(Name = "暗部から溶解")] Option1,
    [Display(Name = "液状メルト")] Option2,
}

[VideoEffect("EEP / ルミナンス・メルト", ["Extended Effects Pack"], ["EEP"], IsAviUtlSupported = false)]
public sealed class LumaMeltEffect : PackEffect
{
    public override string Label => "ルミナンス・メルト";
    public override int EffectId => 15;
    private LumaMeltPreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public LumaMeltPreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private Animation progress = new Animation(0, 0, 100);
    [Display(Name = "進行度", Order = 1)]
    [AnimationSlider("F2", "%", 0, 100)]
    public Animation Progress { get => progress; set => Set(ref progress, value); }

    private Animation softness = new Animation(0.1, 0.01, 0.5);
    [Display(Name = "境界の柔らかさ", Order = 2)]
    [AnimationSlider("F2", "", 0.01, 0.5)]
    public Animation Softness { get => softness; set => Set(ref softness, value); }

    private Animation distortion = new Animation(20, 0, 100);
    [Display(Name = "溶ける変形", Order = 3)]
    [AnimationSlider("F2", "px", 0, 100)]
    public Animation Distortion { get => distortion; set => Set(ref distortion, value); }

    private bool brightFirst = true;
    [Display(Name = "明るい場所から", Order = 4)]
    [ToggleSlider]
    public bool BrightFirst { get => brightFirst; set => Set(ref brightFirst, value); }

    private void ApplyPreset(LumaMeltPreset value)
    {
        switch (value)
        {
            case LumaMeltPreset.Option0:
                Progress = new Animation(0, 0, 100);
                Softness = new Animation(0.1, 0.01, 0.5);
                Distortion = new Animation(20, 0, 100);
                BrightFirst = true;
                break;
            case LumaMeltPreset.Option1:
                Progress = new Animation(0, 0, 100);
                Softness = new Animation(0.1, 0.01, 0.5);
                Distortion = new Animation(20, 0, 100);
                BrightFirst = false;
                break;
            case LumaMeltPreset.Option2:
                Progress = new Animation(0, 0, 100);
                Softness = new Animation(0.25, 0.01, 0.5);
                Distortion = new Animation(80, 0, 100);
                BrightFirst = true;
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [Value(Progress, frame, length, fps), Value(Softness, frame, length, fps), Value(Distortion, frame, length, fps), BrightFirst ? 1 : 0];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [Progress, Softness, Distortion];
}
