// Generated by tools/generate_effects.py. Edit the catalog, then regenerate.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Effects;
using YMM4.ExtendedEffectsPack.Common;

namespace YMM4.ExtendedEffectsPack.Effects;

public enum MotionGhostPreset
{
    [Display(Name = "RGBスプリットゴースト")] Option0,
    [Display(Name = "半透明エコー")] Option1,
    [Display(Name = "フラッシュ残像")] Option2,
}

[VideoEffect("EEP / モーションゴースト・RGB残像", ["Extended Effects Pack"], ["EEP"], IsAviUtlSupported = false)]
public sealed class MotionGhostEffect : PackEffect
{
    public override string Label => "モーションゴースト・RGB残像";
    public override int EffectId => 12;
    private MotionGhostPreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public MotionGhostPreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private Animation delay = new Animation(6, 1, 30);
    [Display(Name = "残像遅延", Order = 1)]
    [AnimationSlider("F2", "フレーム", 1, 30)]
    public Animation Delay { get => delay; set => Set(ref delay, value); }

    private Animation opacity = new Animation(0.5, 0, 1);
    [Display(Name = "ゴースト不透明度", Order = 2)]
    [AnimationSlider("F2", "", 0, 1)]
    public Animation Opacity { get => opacity; set => Set(ref opacity, value); }

    private Animation split = new Animation(15, 0, 50);
    [Display(Name = "RGB分離強度", Order = 3)]
    [AnimationSlider("F2", "px", 0, 50)]
    public Animation Split { get => split; set => Set(ref split, value); }

    private Animation echo = new Animation(5, 0, 30);
    [Display(Name = "拡大エコー率", Order = 4)]
    [AnimationSlider("F2", "%", 0, 30)]
    public Animation Echo { get => echo; set => Set(ref echo, value); }

    private Animation fade = new Animation(2, 1, 5);
    [Display(Name = "フェードアウト速度", Order = 5)]
    [AnimationSlider("F2", "", 1, 5)]
    public Animation Fade { get => fade; set => Set(ref fade, value); }

    private void ApplyPreset(MotionGhostPreset value)
    {
        switch (value)
        {
            case MotionGhostPreset.Option0:
                Delay = new Animation(6, 1, 30);
                Opacity = new Animation(0.5, 0, 1);
                Split = new Animation(15, 0, 50);
                Echo = new Animation(5, 0, 30);
                Fade = new Animation(2, 1, 5);
                break;
            case MotionGhostPreset.Option1:
                Delay = new Animation(12, 1, 30);
                Opacity = new Animation(0.5, 0, 1);
                Split = new Animation(0, 0, 50);
                Echo = new Animation(10, 0, 30);
                Fade = new Animation(2, 1, 5);
                break;
            case MotionGhostPreset.Option2:
                Delay = new Animation(3, 1, 30);
                Opacity = new Animation(0.8, 0, 1);
                Split = new Animation(15, 0, 50);
                Echo = new Animation(5, 0, 30);
                Fade = new Animation(4, 1, 5);
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [Value(Delay, frame, length, fps), Value(Opacity, frame, length, fps), Value(Split, frame, length, fps), Value(Echo, frame, length, fps), Value(Fade, frame, length, fps)];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [Delay, Opacity, Split, Echo, Fade];
}
