// Generated by tools/generate_effects.py. Edit the catalog, then regenerate.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Effects;
using YMM4.ExtendedEffectsPack.Common;

namespace YMM4.ExtendedEffectsPack.Effects;

public enum RetroPixelatePreset
{
    [Display(Name = "レトロ16色")] Option0,
    [Display(Name = "ゲームボーイ風")] Option1,
    [Display(Name = "ヘックス")] Option2,
    [Display(Name = "実用モザイク")] Option3,
}

public enum RetroPixelateShapeChoice
{
    [Display(Name = "四角")] Option0,
    [Display(Name = "円形")] Option1,
    [Display(Name = "六角")] Option2,
}

public enum RetroPixelatePaletteChoice
{
    [Display(Name = "OFF")] Option0,
    [Display(Name = "16色")] Option1,
    [Display(Name = "64色")] Option2,
    [Display(Name = "ゲームボーイ4階調")] Option3,
}

[VideoEffect("EEP / ピクセル化", ["Extended Effects Pack"], ["EEP"], IsAviUtlSupported = false)]
public sealed class RetroPixelateEffect : PackEffect
{
    public override string Label => "ピクセル化";
    public override int EffectId => 2;
    private RetroPixelatePreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public RetroPixelatePreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private Animation sizeX = new Animation(16, 1, 200);
    [Display(Name = "ピクセルサイズX", Order = 1)]
    [AnimationSlider("F2", "px", 1, 200)]
    public Animation SizeX { get => sizeX; set => Set(ref sizeX, value); }

    private Animation sizeY = new Animation(16, 1, 200);
    [Display(Name = "ピクセルサイズY", Order = 2)]
    [AnimationSlider("F2", "px", 1, 200)]
    public Animation SizeY { get => sizeY; set => Set(ref sizeY, value); }

    private RetroPixelateShapeChoice shape = RetroPixelateShapeChoice.Option0;
    [Display(Name = "ドット形状", Order = 3)]
    [EnumComboBox]
    public RetroPixelateShapeChoice Shape { get => shape; set => Set(ref shape, value); }

    private RetroPixelatePaletteChoice palette = RetroPixelatePaletteChoice.Option1;
    [Display(Name = "減色", Order = 4)]
    [EnumComboBox]
    public RetroPixelatePaletteChoice Palette { get => palette; set => Set(ref palette, value); }

    private bool grid = false;
    [Display(Name = "グリッド線", Order = 5)]
    [ToggleSlider]
    public bool Grid { get => grid; set => Set(ref grid, value); }

    private Animation gridOpacity = new Animation(0.6, 0, 1);
    [Display(Name = "グリッド不透明度", Order = 6)]
    [AnimationSlider("F2", "", 0, 1)]
    public Animation GridOpacity { get => gridOpacity; set => Set(ref gridOpacity, value); }

    private bool dither = true;
    [Display(Name = "ディザリング", Order = 7)]
    [ToggleSlider]
    public bool Dither { get => dither; set => Set(ref dither, value); }

    private Color tint = Color.FromRgb(12, 12, 15);
    [Display(Name = "グリッド線色", Order = 8)]
    [ColorPicker]
    public Color Tint { get => tint; set => Set(ref tint, value); }

    private void ApplyPreset(RetroPixelatePreset value)
    {
        switch (value)
        {
            case RetroPixelatePreset.Option0:
                SizeX = new Animation(16, 1, 200);
                SizeY = new Animation(16, 1, 200);
                Shape = RetroPixelateShapeChoice.Option0;
                Palette = RetroPixelatePaletteChoice.Option1;
                Grid = false;
                GridOpacity = new Animation(0.6, 0, 1);
                Dither = true;
                Tint = Color.FromRgb(12, 12, 15);
                break;
            case RetroPixelatePreset.Option1:
                SizeX = new Animation(8, 1, 200);
                SizeY = new Animation(8, 1, 200);
                Shape = RetroPixelateShapeChoice.Option0;
                Palette = RetroPixelatePaletteChoice.Option3;
                Grid = false;
                GridOpacity = new Animation(0.6, 0, 1);
                Dither = true;
                Tint = Color.FromRgb(12, 12, 15);
                break;
            case RetroPixelatePreset.Option2:
                SizeX = new Animation(16, 1, 200);
                SizeY = new Animation(16, 1, 200);
                Shape = RetroPixelateShapeChoice.Option2;
                Palette = RetroPixelatePaletteChoice.Option0;
                Grid = true;
                GridOpacity = new Animation(0.6, 0, 1);
                Dither = true;
                Tint = Color.FromRgb(12, 12, 15);
                break;
            case RetroPixelatePreset.Option3:
                SizeX = new Animation(32, 1, 200);
                SizeY = new Animation(32, 1, 200);
                Shape = RetroPixelateShapeChoice.Option0;
                Palette = RetroPixelatePaletteChoice.Option0;
                Grid = false;
                GridOpacity = new Animation(0.6, 0, 1);
                Dither = false;
                Tint = Color.FromRgb(12, 12, 15);
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [Value(SizeX, frame, length, fps), Value(SizeY, frame, length, fps), (float)Shape, (float)Palette, Grid ? 1 : 0, Value(GridOpacity, frame, length, fps), Dither ? 1 : 0];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [SizeX, SizeY, GridOpacity];
    internal override Vector4 ReadTint() => new(Tint.R / 255f, Tint.G / 255f, Tint.B / 255f, Tint.A / 255f);
}
