// Generated by tools/generate_effects.py. Edit the catalog, then regenerate.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Effects;
using YMM4.ExtendedEffectsPack.Common;

namespace YMM4.ExtendedEffectsPack.Effects;

public enum RgbGamingPreset
{
    [Display(Name = "激流ウェーブ")] Option0,
    [Display(Name = "爆速カラー")] Option1,
    [Display(Name = "ネオン輪郭")] Option2,
    [Display(Name = "ゆったりムーディー")] Option3,
}

public enum RgbGamingModeChoice
{
    [Display(Name = "全体色相回転")] Option0,
    [Display(Name = "流動光波")] Option1,
    [Display(Name = "輪郭ネオン")] Option2,
}

public enum RgbGamingBlendChoice
{
    [Display(Name = "通常")] Option0,
    [Display(Name = "加算")] Option1,
    [Display(Name = "スクリーン")] Option2,
    [Display(Name = "色相置換")] Option3,
}

[VideoEffect("EEP / 七色ゲーミング", ["Extended Effects Pack"], ["EEP"], IsAviUtlSupported = false)]
public sealed class RgbGamingEffect : PackEffect
{
    public override string Label => "七色ゲーミング";
    public override int EffectId => 4;
    private RgbGamingPreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public RgbGamingPreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private RgbGamingModeChoice mode = RgbGamingModeChoice.Option1;
    [Display(Name = "発光モード", Order = 1)]
    [EnumComboBox]
    public RgbGamingModeChoice Mode { get => mode; set => Set(ref mode, value); }

    private Animation speed = new Animation(5, 0, 50);
    [Display(Name = "回転速度", Order = 2)]
    [AnimationSlider("F2", "", 0, 50)]
    public Animation Speed { get => speed; set => Set(ref speed, value); }

    private Animation angle = new Animation(45, 0, 360);
    [Display(Name = "波の角度", Order = 3)]
    [AnimationSlider("F2", "°", 0, 360)]
    public Animation Angle { get => angle; set => Set(ref angle, value); }

    private Animation intensity = new Animation(2, 1, 5);
    [Display(Name = "発光強度", Order = 4)]
    [AnimationSlider("F2", "", 1, 5)]
    public Animation Intensity { get => intensity; set => Set(ref intensity, value); }

    private RgbGamingBlendChoice blend = RgbGamingBlendChoice.Option0;
    [Display(Name = "合成モード", Order = 5)]
    [EnumComboBox]
    public RgbGamingBlendChoice Blend { get => blend; set => Set(ref blend, value); }

    private void ApplyPreset(RgbGamingPreset value)
    {
        switch (value)
        {
            case RgbGamingPreset.Option0:
                Mode = RgbGamingModeChoice.Option1;
                Speed = new Animation(5, 0, 50);
                Angle = new Animation(45, 0, 360);
                Intensity = new Animation(2, 1, 5);
                Blend = RgbGamingBlendChoice.Option0;
                break;
            case RgbGamingPreset.Option1:
                Mode = RgbGamingModeChoice.Option1;
                Speed = new Animation(40, 0, 50);
                Angle = new Animation(45, 0, 360);
                Intensity = new Animation(4, 1, 5);
                Blend = RgbGamingBlendChoice.Option1;
                break;
            case RgbGamingPreset.Option2:
                Mode = RgbGamingModeChoice.Option2;
                Speed = new Animation(3, 0, 50);
                Angle = new Animation(45, 0, 360);
                Intensity = new Animation(2, 1, 5);
                Blend = RgbGamingBlendChoice.Option0;
                break;
            case RgbGamingPreset.Option3:
                Mode = RgbGamingModeChoice.Option1;
                Speed = new Animation(0.4, 0, 50);
                Angle = new Animation(45, 0, 360);
                Intensity = new Animation(1, 1, 5);
                Blend = RgbGamingBlendChoice.Option2;
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [(float)Mode, Value(Speed, frame, length, fps), Value(Angle, frame, length, fps), Value(Intensity, frame, length, fps), (float)Blend];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [Speed, Angle, Intensity];
}
