// Generated by tools/generate_effects.py. Edit the catalog, then regenerate.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Effects;
using YMM4.ExtendedEffectsPack.Common;

namespace YMM4.ExtendedEffectsPack.Effects;

public enum TheaterCurtainPreset
{
    [Display(Name = "クラシック深紅")] Option0,
    [Display(Name = "エレガントゴールド")] Option1,
    [Display(Name = "モダンブラック")] Option2,
    [Display(Name = "ロイヤルブルー")] Option3,
}

public enum TheaterCurtainOpeningChoice
{
    [Display(Name = "中央両開き")] Option0,
    [Display(Name = "左へ片引き")] Option1,
    [Display(Name = "右へ片引き")] Option2,
}

[VideoEffect("EEP / 劇場カーテン", ["Extended Effects Pack"], ["EEP"], IsAviUtlSupported = false)]
public sealed class TheaterCurtainEffect : PackEffect
{
    public override string Label => "劇場カーテン";
    public override int EffectId => 0;
    private TheaterCurtainPreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public TheaterCurtainPreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private Animation progress = new Animation(0, 0, 100);
    [Display(Name = "進行度", Order = 1)]
    [AnimationSlider("F2", "%", 0, 100)]
    public Animation Progress { get => progress; set => Set(ref progress, value); }

    private TheaterCurtainOpeningChoice opening = TheaterCurtainOpeningChoice.Option0;
    [Display(Name = "開き方", Order = 2)]
    [EnumComboBox]
    public TheaterCurtainOpeningChoice Opening { get => opening; set => Set(ref opening, value); }

    private Animation folds = new Animation(12, 4, 30);
    [Display(Name = "ヒダの数", Order = 3)]
    [AnimationSlider("F2", "", 4, 30)]
    public Animation Folds { get => folds; set => Set(ref folds, value); }

    private bool gloss = true;
    [Display(Name = "ベルベット光沢", Order = 4)]
    [ToggleSlider]
    public bool Gloss { get => gloss; set => Set(ref gloss, value); }

    private bool fringe = true;
    [Display(Name = "金フリンジ", Order = 5)]
    [ToggleSlider]
    public bool Fringe { get => fringe; set => Set(ref fringe, value); }

    private Color tint = Color.FromRgb(138, 11, 26);
    [Display(Name = "カーテン色", Order = 6)]
    [ColorPicker]
    public Color Tint { get => tint; set => Set(ref tint, value); }

    private void ApplyPreset(TheaterCurtainPreset value)
    {
        switch (value)
        {
            case TheaterCurtainPreset.Option0:
                Progress = new Animation(0, 0, 100);
                Opening = TheaterCurtainOpeningChoice.Option0;
                Folds = new Animation(12, 4, 30);
                Gloss = true;
                Fringe = true;
                Tint = Color.FromRgb(138, 11, 26);
                break;
            case TheaterCurtainPreset.Option1:
                Progress = new Animation(0, 0, 100);
                Opening = TheaterCurtainOpeningChoice.Option0;
                Folds = new Animation(18, 4, 30);
                Gloss = true;
                Fringe = true;
                Tint = Color.FromRgb(202, 157, 46);
                break;
            case TheaterCurtainPreset.Option2:
                Progress = new Animation(0, 0, 100);
                Opening = TheaterCurtainOpeningChoice.Option0;
                Folds = new Animation(12, 4, 30);
                Gloss = false;
                Fringe = false;
                Tint = Color.FromRgb(20, 20, 24);
                break;
            case TheaterCurtainPreset.Option3:
                Progress = new Animation(0, 0, 100);
                Opening = TheaterCurtainOpeningChoice.Option0;
                Folds = new Animation(12, 4, 30);
                Gloss = true;
                Fringe = true;
                Tint = Color.FromRgb(25, 40, 145);
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [Value(Progress, frame, length, fps), (float)Opening, Value(Folds, frame, length, fps), Gloss ? 1 : 0, Fringe ? 1 : 0];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [Progress, Folds];
    internal override Vector4 ReadTint() => new(Tint.R / 255f, Tint.G / 255f, Tint.B / 255f, Tint.A / 255f);
}
