// Generated by tools/generate_effects.py. Edit the catalog, then regenerate.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Effects;
using YMM4.ExtendedEffectsPack.Common;

namespace YMM4.ExtendedEffectsPack.Effects;

public enum ThunderPreset
{
    [Display(Name = "超雷撃")] Option0,
    [Display(Name = "覚醒帯電オーラ")] Option1,
    [Display(Name = "漆黒の魔雷")] Option2,
}

public enum ThunderModeChoice
{
    [Display(Name = "落雷フラッシュ")] Option0,
    [Display(Name = "輪郭帯電オーラ")] Option1,
}

[VideoEffect("EEP / サンダー", ["Extended Effects Pack"], ["EEP"], IsAviUtlSupported = false)]
public sealed class ThunderEffect : PackEffect
{
    public override string Label => "サンダー";
    public override int EffectId => 9;
    private ThunderPreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public ThunderPreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private ThunderModeChoice mode = ThunderModeChoice.Option0;
    [Display(Name = "動作モード", Order = 1)]
    [EnumComboBox]
    public ThunderModeChoice Mode { get => mode; set => Set(ref mode, value); }

    private Animation frequency = new Animation(12, 1, 30);
    [Display(Name = "バチバチ頻度", Order = 2)]
    [AnimationSlider("F2", "fps", 1, 30)]
    public Animation Frequency { get => frequency; set => Set(ref frequency, value); }

    private Animation thickness = new Animation(4, 1, 20);
    [Display(Name = "稲妻の太さ", Order = 3)]
    [AnimationSlider("F2", "px", 1, 20)]
    public Animation Thickness { get => thickness; set => Set(ref thickness, value); }

    private Animation jaggedness = new Animation(6, 1, 10);
    [Display(Name = "ギザギザ・分岐度", Order = 4)]
    [AnimationSlider("F2", "", 1, 10)]
    public Animation Jaggedness { get => jaggedness; set => Set(ref jaggedness, value); }

    private Animation flash = new Animation(0.7, 0, 1);
    [Display(Name = "閃光強度", Order = 5)]
    [AnimationSlider("F2", "", 0, 1)]
    public Animation Flash { get => flash; set => Set(ref flash, value); }

    private Color tint = Color.FromRgb(176, 226, 255);
    [Display(Name = "電撃カラー", Order = 6)]
    [ColorPicker]
    public Color Tint { get => tint; set => Set(ref tint, value); }

    private void ApplyPreset(ThunderPreset value)
    {
        switch (value)
        {
            case ThunderPreset.Option0:
                Mode = ThunderModeChoice.Option0;
                Frequency = new Animation(12, 1, 30);
                Thickness = new Animation(4, 1, 20);
                Jaggedness = new Animation(6, 1, 10);
                Flash = new Animation(0.7, 0, 1);
                Tint = Color.FromRgb(176, 226, 255);
                break;
            case ThunderPreset.Option1:
                Mode = ThunderModeChoice.Option1;
                Frequency = new Animation(12, 1, 30);
                Thickness = new Animation(4, 1, 20);
                Jaggedness = new Animation(6, 1, 10);
                Flash = new Animation(0, 0, 1);
                Tint = Color.FromRgb(176, 226, 255);
                break;
            case ThunderPreset.Option2:
                Mode = ThunderModeChoice.Option1;
                Frequency = new Animation(12, 1, 30);
                Thickness = new Animation(4, 1, 20);
                Jaggedness = new Animation(6, 1, 10);
                Flash = new Animation(0, 0, 1);
                Tint = Color.FromRgb(174, 50, 255);
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [(float)Mode, Value(Frequency, frame, length, fps), Value(Thickness, frame, length, fps), Value(Jaggedness, frame, length, fps), Value(Flash, frame, length, fps)];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [Frequency, Thickness, Jaggedness, Flash];
    internal override Vector4 ReadTint() => new(Tint.R / 255f, Tint.G / 255f, Tint.B / 255f, Tint.A / 255f);
}
