// Generated by tools/generate_effects.py. Edit the catalog, then regenerate.
using System.ComponentModel.DataAnnotations;
using System.Numerics;
using System.Windows.Media;
using Newtonsoft.Json;
using YukkuriMovieMaker.Commons;
using YukkuriMovieMaker.Controls;
using YukkuriMovieMaker.Plugin.Effects;
using YMM4.ExtendedEffectsPack.Common;

namespace YMM4.ExtendedEffectsPack.Effects;

public enum VhsGlitchPreset
{
    [Display(Name = "80sホームビデオ")] Option0,
    [Display(Name = "激しいトラッキング")] Option1,
    [Display(Name = "深夜のホラーテープ")] Option2,
}

[VideoEffect("EEP / レトロVHSグリッチ", ["Extended Effects Pack"], ["EEP"], IsAviUtlSupported = false)]
public sealed class VhsGlitchEffect : PackEffect
{
    public override string Label => "レトロVHSグリッチ";
    public override int EffectId => 13;
    private VhsGlitchPreset preset;
    [JsonProperty(Order = -100)]
    [Display(Name = "プリセット", Order = 0, Description = "選択すると各設定とキーフレームを初期化します。")]
    [EnumComboBox]
    public VhsGlitchPreset Preset
    {
        get => preset;
        set { if (Set(ref preset, value)) ApplyPreset(value); }
    }

    private Animation intensity = new Animation(0.3, 0, 1);
    [Display(Name = "グリッチ強度", Order = 1)]
    [AnimationSlider("F2", "", 0, 1)]
    public Animation Intensity { get => intensity; set => Set(ref intensity, value); }

    private Animation scanlines = new Animation(0.4, 0, 1);
    [Display(Name = "走査線濃度", Order = 2)]
    [AnimationSlider("F2", "", 0, 1)]
    public Animation Scanlines { get => scanlines; set => Set(ref scanlines, value); }

    private bool tracking = true;
    [Display(Name = "下部トラッキング帯", Order = 3)]
    [ToggleSlider]
    public bool Tracking { get => tracking; set => Set(ref tracking, value); }

    private Animation frequency = new Animation(0.3, 0, 1);
    [Display(Name = "水平同期ズレ頻度", Order = 4)]
    [AnimationSlider("F2", "", 0, 1)]
    public Animation Frequency { get => frequency; set => Set(ref frequency, value); }

    private bool fade = true;
    [Display(Name = "テープ色あせ", Order = 5)]
    [ToggleSlider]
    public bool Fade { get => fade; set => Set(ref fade, value); }

    private void ApplyPreset(VhsGlitchPreset value)
    {
        switch (value)
        {
            case VhsGlitchPreset.Option0:
                Intensity = new Animation(0.3, 0, 1);
                Scanlines = new Animation(0.4, 0, 1);
                Tracking = true;
                Frequency = new Animation(0.3, 0, 1);
                Fade = true;
                break;
            case VhsGlitchPreset.Option1:
                Intensity = new Animation(0.9, 0, 1);
                Scanlines = new Animation(0.4, 0, 1);
                Tracking = true;
                Frequency = new Animation(0.8, 0, 1);
                Fade = true;
                break;
            case VhsGlitchPreset.Option2:
                Intensity = new Animation(0.6, 0, 1);
                Scanlines = new Animation(0.8, 0, 1);
                Tracking = true;
                Frequency = new Animation(0.3, 0, 1);
                Fade = true;
                break;
        }
    }

    internal override float[] ReadValues(double frame, double length, int fps) =>
        [Value(Intensity, frame, length, fps), Value(Scanlines, frame, length, fps), Tracking ? 1 : 0, Value(Frequency, frame, length, fps), Fade ? 1 : 0];
    protected override IEnumerable<IAnimatable> GetAnimatables() => [Intensity, Scanlines, Frequency];
}
